[package]
name = "starlight-neon"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.28"

[profile.release]
opt-level = "s"

[profile.dev]
opt-level = "s"