name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install NodeJS V12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Yarn
      run: yarn --ignore-scripts
    - name: tsc
      run: tsc -p . --noEmit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        job-name: tsc